### ISSUE TITLE
Display current build number with :display_info_after_build

### ISSUE THREAD

**Issue by ryanlindsey** [mcavallo/middleman-build-info#2]
When `:display_info_after_build => true` the build version rendered is incremented and does not reflect the current build but rather the next. I was wondering if it would make sense to remove the increment but noticed it would have other unintended consequences.

I'm not sure how you feel about this, but would be happy to work on a PR if you're interested.

**Comment by mcavallo** [comment]
Thanks for taking the time to report this. We use this extension in several projects and we never noticed this issue. You are more than welcome to send a PR but still I would like to try to reproduce this before committing to change anything.
